### ISSUE TITLE
Support newer, shorter naming convention

### ISSUE THREAD

**Issue by mosabua** [takari/jdkget#17]
The latest JDK downloads use a different naming convention. E.g. the currently latest one available at http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

uses the ID string "8u111". 

Also see http://www.oracle.com/technetwork/java/javase/overview/jdk-version-number-scheme-1918258.html

**Comment by mosabua** [comment]
Fyi  @atanasenko this would make it more user friendly in looper.yml files imho

**Comment by mosabua** [comment]
Currently using 8u111 in looper I get 

 Checking out Revision 2fc8b0e674031aeab7ba38913af2425f5df701b1 (origin/master)
11:14:22 FATAL: Unable to find jdk release for version 1.8.0_111
11:14:22 java.lang.IllegalStateException: Unable to find jdk release for version 1.8.0_111
11:14:22    at io.takari.jdkget.JdkReleases.select(JdkReleases.java:96)
11:14:22    at io.takari.looper.job.provisioner.tools.jdk.JDKToolDefinition.normalize(JDKToolDefinition.java:68)
11:14:22    at io.takari.looper.job.provisioner.tools.jdk.JDKToolDefinition.createTool(JDKToolDefinition.java:56)
11:14:22    at io.takari.looper.job.provisioner.tools.jdk.JDKToolDefinition.createTool(JDKToolDefinition.java:1)
11:14:22    at io.takari.looper.job.provisioner.ToolDefinition.getInstallation(ToolDefinition.java:55)
11:14:22    at io.takari.looper.job.config.impl.ToolSelector.addTool(ToolSelector.java:47)
11:14:22    at io.takari.looper.job.config.impl.ToolSelector.configure(ToolSelector.java:33)
11:14:22    at io.takari.looper.job.LooperBuild$Exec.doRun(LooperBuild.java:858)
11:14:22    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
11:14:22    at hudson.model.Run.execute(Run.java:1720)
11:14:22    at io.takari.looper.job.LooperBuild.run(LooperBuild.java:587)
11:14:22    at hudson.model.ResourceController.execute(ResourceController.java:98)
11:14:22    at hudson.model.Executor.run(Executor.java:404)

Looks like we might have to update the list as well.

**Comment by mosabua** [comment]
This is now working since 8u111 is now provisioned. Next build/release will permanently fix this.
